export const ADMIN_ROUTE = '/admin'
export const ADMIN_ORDERS_ROUTE = '/adminorders'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE='/'
export const PICTURE_ROUTE='/catalog/'
export const ORDER_ROUTE = '/order'
export const BASKET_ROUTE = '/basket'